# Generated by Django 4.0.6 on 2022-07-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictAndCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Tuman yoki Shaxar nomi')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foreign_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Chet tili nomi')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Qiziqish nomi')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Mahalla nomi')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('districtandcity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.districtandcity', verbose_name='Qaysi tuman (shaxar)da joylashgan')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Imkonyatlar nomi')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='OTM nomi')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=250, verbose_name='F.I.O')),
                ('student_img', models.ImageField(upload_to='student_images/')),
                ('email', models.EmailField(max_length=250, verbose_name='E-Pochta')),
                ('birth_day', models.DateField(verbose_name="Tug'ulgan sana")),
                ('driver_l', models.CharField(choices=[('Bor', 'Bor'), ('Yoq', 'Yoq')], default='Yoq', max_length=250, verbose_name='Haydovchilik guvohnomasi')),
                ('idea', models.CharField(choices=[('Bor', 'Bor'), ('Yoq', 'Yoq')], default='Bor', max_length=250, verbose_name="Bizsess g'oya")),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('districtandcity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.districtandcity', verbose_name='Yashaydigan tumani')),
                ('foreign_language', models.ManyToManyField(related_name='foreign_language', to='main.foreign_language', verbose_name='Chet tili')),
                ('interest', models.ManyToManyField(related_name='interest', to='main.interest', verbose_name='Qiziqishlar')),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.neighborhood', verbose_name='Yashaydigan mahalla')),
                ('opportunity', models.ManyToManyField(related_name='opportunity', to='main.opportunity', verbose_name='Imkonyatlari')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Maktab raqami')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('districtandcity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.districtandcity')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Kollej nomi')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('districtandcity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.districtandcity')),
            ],
        ),
    ]
